select * from  product_sales;

-- 1. Find the total revenue generated by each product category.
select    Category, Sum(Revenue) as TotalRevenue_byeach_category from product_sales
group by Category;

-- 2.Identify the top 5 best-selling products based on total quantity sold

select Product_Name, MAX(Quantity) AS Max_Quantity
from product_sales
group by Product_Name
order by  Max_Quantity desc
LIMIT 5;

-- 3. Show the month-wise total sales revenue trend for the entire dataset.
select month(Order_Date) as Month_ofthe_sale  , sum(Revenue) from product_sales
group by month(Order_Date) 
order by month(Order_Date);

--  4. Which state has generated the highest total profit?
select state, max(Profit) as High_profit from product_sales
group by state
order by max(Profit) Desc;


-- 5.Find the total quantity sold in each region. 
select region as Region, sum(Quantity) as Total_Quantity  from product_sales
group by region ;

-- 6. List all products that have a profit margin greater than 30%
select * from product_sales
where profit > Unit_Price * 0.30 ;

-- 7. Which customer has generated the highest total revenue?
select Customer_Name , max(Revenue) from product_sales
group by Customer_Name
order by max(Revenue) DESC;

-- 8. Find the average unit price for each product category.
select Category, avg(Unit_Price) as Avg_unit_price from product_sales
group by Category; 

--  9. List all sales records where the quantity purchased is more than 3.
select * from product_sales
where Quantity > 3 
order by Order_ID;

-- 10. Identify customers who appear in multiple cities (same customer name, different cities).
select Customer_Name
from product_sales
group by  Customer_Name
having COUNT(DISTINCT City) > 1;
